### ISSUE TITLE
Hacktoberfest 2021: Screenshots, please!

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/termage#71]
`termage` is a tool to view and browse images in the browser.
However, it's hard to "see" that this is true by looking at the README. What the README needs is screenshots!

2 images should be good enough.
- [ ] A still image showing what it looks like to view a JPEG, PNG, or un-animated GIF
- [ ] An animated GIF or MP4 showing what it looks like to view an animated GIF

These screenshots should be saved to the `_resources` folder.

Happy hacking! :jack_o_lantern:

Edit: The image being viewed should be in the [public domain](https://en.wikipedia.org/wiki/Public_domain).

**Comment by juanmaotegui** [comment]
Can I work on this?
